@extends('errors.layout')
@section('code', '403')
@section('title', 'Akses tidak diizinkan')
@section('message', 'Akun Anda tidak memiliki izin untuk membuka halaman ini.')
@section('action', url('/'))
@section('button', 'Kembali ke halaman utama')
