@extends('errors.layout')
@section('code', '500')
@section('title', 'Terjadi gangguan sistem')
@section('message', 'Permintaan belum dapat diproses. Silakan coba kembali beberapa saat lagi.')
@section('action', url('/'))
@section('button', 'Kembali ke halaman utama')
