@extends('errors.layout')
@section('code', '503')
@section('title', 'Layanan sedang dalam pemeliharaan')
@section('message', 'SiPrega sedang diperbarui. Silakan akses kembali beberapa saat lagi.')
@section('action', url('/'))
@section('button', 'Muat ulang')
