@extends('layouts.app')
@section('title', 'Detail Pengajuan')
@section('page-title', 'Detail Pengajuan')
@section('page-subtitle', $leaveRequest->type === 'sick' ? 'Pengajuan sakit' : 'Pengajuan izin')
@section('content')
<div class="mb-4"><a class="btn btn-light" href="{{ route('employee.leave-requests.index') }}">← Kembali</a></div>
<div class="row g-4">
    <div class="col-lg-5"><div class="card stat-card h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Informasi Pengajuan</h2><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Jenis</span><strong>{{ $leaveRequest->type === 'sick' ? 'Sakit' : 'Izin' }}</strong></div><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Tanggal</span><span>{{ $leaveRequest->start_date->format('d/m/Y') }}–{{ $leaveRequest->start_date->copy()->addDays($leaveRequest->duration - 1)->format('d/m/Y') }}</span></div><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Durasi</span><span>{{ $leaveRequest->duration }} hari</span></div><div class="d-flex justify-content-between py-3"><span class="text-muted">Status</span><strong>{{ $leaveRequest->status === 'approved' ? 'Disetujui' : ($leaveRequest->status === 'rejected' ? 'Ditolak' : 'Menunggu') }}</strong></div></div></div></div>
    <div class="col-lg-7"><div class="card stat-card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Alasan</h2><p style="white-space:pre-line">{{ $leaveRequest->reason }}</p>@if($leaveRequest->attachment)<a class="btn btn-sm btn-outline-primary" href="{{ route('employee.leave-requests.attachment', $leaveRequest) }}">Unduh Lampiran</a>@endif</div></div><div class="card stat-card"><div class="card-body p-4"><h2 class="h5 mb-3">Hasil Peninjauan</h2>@if($leaveRequest->status === 'pending')<p class="text-muted">Pengajuan sedang menunggu keputusan administrator.</p><form method="POST" action="{{ route('employee.leave-requests.destroy', $leaveRequest) }}" onsubmit="return confirm('Batalkan pengajuan ini?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Batalkan Pengajuan</button></form>@else<div class="small text-muted">Diproses {{ $leaveRequest->reviewed_at ? $leaveRequest->reviewed_at->format('d/m/Y H:i') : '-' }}</div><div class="mt-3"><strong>Catatan admin</strong><p class="mb-0">{{ $leaveRequest->review_note ?: '-' }}</p></div>@endif</div></div></div>
</div>
@endsection
