@extends('layouts.app')
@section('title', 'Detail Absensi')
@section('page-title', 'Detail Absensi')
@section('page-subtitle', 'Catatan tanggal shift '.$attendance->attendance_date->format('d/m/Y'))
@section('content')
<div class="mb-4"><a class="btn btn-light" href="{{ route('employee.attendances.index') }}">← Kembali</a></div>
<div class="row g-4">
    <div class="col-lg-5"><div class="card stat-card h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Informasi Kehadiran</h2><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Jadwal</span><strong>{{ optional($attendance->workSchedule)->name ?: '-' }}</strong></div><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Jenis</span><span>{{ optional($attendance->workSchedule)->shift_type === 'night' ? 'Shift Malam' : (optional($attendance->workSchedule)->shift_type === 'day' ? 'Shift Siang' : 'Jadwal Tetap') }}</span></div><div class="d-flex justify-content-between border-bottom py-3"><span class="text-muted">Lokasi</span><span>{{ optional($attendance->location)->name ?: '-' }}</span></div><div class="d-flex justify-content-between py-3"><span class="text-muted">Status</span><strong>{{ $attendance->check_in_status === 'late' ? 'Terlambat' : 'Tepat waktu' }}</strong></div></div></div></div>
    <div class="col-lg-7"><div class="card stat-card h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Waktu Absensi</h2><div class="row g-3"><div class="col-sm-6"><div class="border rounded-3 p-3"><div class="text-muted small">Absen Masuk</div><div class="fs-4 fw-semibold">{{ $attendance->check_in ? $attendance->check_in->format('H:i:s') : '-' }}</div><div class="small text-muted">Akurasi {{ $attendance->check_in_accuracy !== null ? number_format((float) $attendance->check_in_accuracy, 0).' m' : '-' }} · Jarak {{ $attendance->check_in_distance !== null ? number_format((float) $attendance->check_in_distance, 0).' m' : '-' }}</div></div></div><div class="col-sm-6"><div class="border rounded-3 p-3"><div class="text-muted small">Absen Pulang</div><div class="fs-4 fw-semibold">{{ $attendance->check_out ? $attendance->check_out->format('H:i:s') : '-' }}</div><div class="small text-muted">Akurasi {{ $attendance->check_out_accuracy !== null ? number_format((float) $attendance->check_out_accuracy, 0).' m' : '-' }} · Jarak {{ $attendance->check_out_distance !== null ? number_format((float) $attendance->check_out_distance, 0).' m' : '-' }}</div></div></div></div>@if($attendance->early_checkout_reason)<div class="alert alert-warning mt-3 mb-0"><strong>Alasan pulang lebih awal:</strong> {{ $attendance->early_checkout_reason }}</div>@endif</div></div></div>
</div>
@endsection
